-- MySQL Script generated by MySQL Workbench
-- Mon Nov 24 11:24:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema memory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema memory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `memory` DEFAULT CHARACTER SET utf8mb4 ;
USE `memory` ;

-- -----------------------------------------------------
-- Table `memory`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memory`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `mot_de_passe` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `nom` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `prenom` VARCHAR(50) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `memory`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `memory`.`scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temps` TIME NULL DEFAULT NULL,
  `nombre_paires` INT NULL DEFAULT NULL,
  `date_creation` DATETIME NULL DEFAULT NULL,
  `id_utilisateur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scores_utilisateurs_idx` (`id_utilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_scores_utilisateurs`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `memory`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
